### ISSUE TITLE
Hi, I have this problem Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by sty945** [hankcs/AhoCorasickDoubleArrayTrie#15]
Hi,My java version is jdk 1.6, when i run the TestAhoCorasickDoubleArrayTrie.java, my result is below:
```
"C:\Program Files\Java\jdk1.6.0_30\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3\lib\idea_rt.jar=65102:C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3\plugins\junit\lib\junit5-rt.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\jce.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\resources.jar;C:\Program Files\Java\jdk1.6.0_30\jre\lib\rt.jar;D:\sty\sogou\codeFile\AhoCorasickDoubleArrayTrie-master\target\test-classes;D:\sty\sogou\codeFile\AhoCorasickDoubleArrayTrie-master\target\classes;C:\Users\sutaoyu\.m2\repository\junit\junit\3.8.1\junit-3.8.1.jar;C:\Users\sutaoyu\.m2\repository\org\ahocorasick\ahocorasick\0.2.3\ahocorasick-0.2.3.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 TestAhoCorasickDoubleArrayTrie
[1:3]=he
[1:5]=hers
[[1:3]=he, [1:5]=hers]
Testing cancellation

java.lang.UnsupportedClassVersionError: org/ahocorasick/trie/Trie : Unsupported major.minor version 51.0

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at TestAhoCorasickDoubleArrayTrie.runTest(TestAhoCorasickDoubleArrayTrie.java:234)
	at TestAhoCorasickDoubleArrayTrie.testBenchmark(TestAhoCorasickDoubleArrayTrie.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at com.intellij.junit3.JUnit3IdeaTestRunner.doRun(JUnit3IdeaTestRunner.java:113)
	at junit.textui.TestRunner.doRun(TestRunner.java:109)
	at com.intellij.junit3.JUnit3IdeaTestRunner.startRunnerWithArgs(JUnit3IdeaTestRunner.java:45)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Saving acdat to: C:\Users\sutaoyu\AppData\Local\Temp\/acdat.tmp
Loading acdat from: C:\Users\sutaoyu\AppData\Local\Temp\/acdat.tmp
[1:3]=he
[1:5]=hers
[[1:3]=he, [1:5]=hers]

Process finished with exit code -1
```
I wonder why this problem caused? Thank you very much!!!

**Comment by hankcs** [comment]
See https://github.com/hankcs/AhoCorasickDoubleArrayTrie/blob/master/src/test/java/TestAhoCorasickDoubleArrayTrie.java#L272

**Comment by sty945** [comment]
Thank you very much!! I solved this problem before by rewriting your code in java 1.6！！You code is very fantastic ! But i test this code to find about 520 words in a 8G txt, it spent several  hours. In my opinion, if you write this code in c/c++, the code will be more faster!!!
